### PR TITLE
Include concepts from MIX in MIX2

### PR DESCRIPTION
**Pull request by carlosjoan91**
This incorporates the suggestions in https://github.com/w3c/webappsec-mixed-content/issues/25 to merge MIX onto MIX2, so MIX2 can completely replace it.

### CODE REVIEW

**Comment by annevk** [comment]
What would make this easier to review if we had a diff between MIX and MIX2 (done in the way you did here) using https://services.w3.org/htmldiff.

**Comment by carlosjoan91** [comment]
Diff is attached. I can also add it as a file on the PR, but I'm not sure it would make sense for it to live on the repository, let me know if you'd prefer that though.
[diff.zip](https://github.com/w3c/webappsec-mixed-content/files/4495721/diff.zip)

**Comment by annevk** [comment]
That's a diff of the source, not the generated output, right?

**Comment by carlosjoan91** [comment]
Yeah, sorry that was not intended, the proper one is [this one](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fraw.githubusercontent.com%2Fw3c%2Fwebappsec-mixed-content%2Fmaster%2Findex.html&doc2=https%3A%2F%2Fraw.githubusercontent.com%2Fw3c%2Fwebappsec-mixed-content%2Ff24e18edad6d206caff96d90cef9bbdd63e57792%2Flevel2.fpwd.html).

**Comment by annevk** [comment]
Thank you, this largely looks like an improvement to me and I can think any further issues are best discussed after this is done. One thing that seems problematic though is the omission of the Acknowledgments section. Ideally those only ever grow.

**Comment by carlosjoan91** [comment]
Thanks for reviewing. I went ahead and copied/slightly updated the acknowledgements from MIX since they are still valid on this version. Happy to keep adding/updating as needed.

**Comment by annevk** [comment]
Looks good to me. @estark37 or @mikewest should probably do a final pass.

**Comment by carlosjoan91** [comment]
@mikewest: Assigned to you for a final pass (since @estark37 already did the initial review round). Can you please take a look? Thanks

**Comment by mikewest** [comment]
I tried to get to this today, and failed. It's top of my list for the morning (even on my calendar!). Apologies for the delay. :(

**Pull request merged**
