### PR TITLE
Add FPWD document for MIX2

### PR DESCRIPTION
**Pull request by carlosjoan91**

### CODE REVIEW

**Comment by carlosjoan91** [comment]
@mikewest PTAL? Thanks.

**Comment by carlosjoan91** [comment]
Added the commit for using level2.html as FPWD. Quick check before merging though, won't that cause https://w3c.github.io/webappsec-mixed-content/level2.html to point to the new file though (causing it to say Working Draft as oppossed to Editor's Draft)? If so, is that ok?

**Comment by carlosjoan91** [comment]
@mikewest, ping

**Comment by mikewest** [comment]
> @mikewest, ping

Sorry, this fell off my radar.

I think what I'd suggest is that `level2.src.html` continue to call itself an editor's draft, and that you build a distinct `level2.fpwd.html` file by calling `bikeshed spec --md-status=FPWD level2.src.html level2.fpwd.html`.

**Comment by carlosjoan91** [comment]
Sorry, I missed the response, then forgot this wasn't merged yet. Finally merging this in preparation for further changes to MIX2

**Pull request merged**
